version: "3.8"

services:
    db:
        image: mysql
        container_name: db_sfcover
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sf6-cover
            MYSQL_USER: symfony
            MYSQL_PASSWORD: mypassword
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmnin_sfcover
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    www:
        build: docker
        container_name: www_sfcover
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ./docker/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        networks:
            - dev

    mailer:
        image: schickling/mailcatcher
        container_name: mailcatcher_sfcover
        ports: ["1025", "1080"]
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:
